[build]
  command = "npm run build"  # Det här bygger din Next.js-app
  publish = ".next"  # Publikationen ska vara din .next-mapp (där din byggda app finns)

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Lägg till Netlify-pluginet för Next.js för att hantera SSR
